server:
  servlet:
    context-path: /desafio-java/api

spring:
  datasource:
    url:  jdbc:h2:mem:demodb
    username: sa
    password:
    dbcp2:
      driver-class-name: org.h2.Driver

  h2:
    console:
      enable: true
      path: /h2-console

spring-doc:
  swagger-ui:
    path: /public/swagger